#https://www.datacamp.com/community/tutorials/bootstrap-r

head(iris)

library(boot)

foo <- function(data, indices, cor.type){
  dt<-data[indices,]
  c(
    cor(dt[,1], dt[,2], method=cor.type),
    median(dt[,1]),
    median(dt[,2])
  )
}

set.seed(12345)
myBootstrap <- boot(iris, foo, R=1000, cor.type='s')

#$t0 contains values of our statistic(s) in original, full, dataset
myBootstrap$t0

#$t contains R values of our statistic(s) generated by the bootstrap procedure (bootstrap realizations of T)
myBootstrap$t

colMeans(myBootstrap$t)-myBootstrap$t0

apply(myBootstrap$t,2,sd)

plot(myBootstrap, index=3)

boot.ci(myBootstrap, index=1,type=c('basic','perc'))

tableOfIndices<-boot.array(myBootstrap, indices=T)




























